namespace hakanai.dal.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PhotographIDAutogenerated : DbMigration
    {
        public override void Up()
        {
            AlterColumn("dbo.Photographs", "PhotographyId", c => c.Guid(nullable: false, identity: true));
        }
        
        public override void Down()
        {
            AlterColumn("dbo.Photographs", "PhotographyId", c => c.Guid(nullable: false));
        }
    }
}
